name: Daily Meditation AI Agent

on:
  schedule:
    # روزانه در حدود ساعت 21:00 به وقت تهران (16:30 UTC)
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  run-ai-agent:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run AI Agent
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        python main.py
